# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PairwiseLik <- function(yvec, z, X, index, beta, grad) {
    .Call('_dPLR_PairwiseLik', PACKAGE = 'dPLR', yvec, z, X, index, beta, grad)
}

PairwiseLikDeriv <- function(yvec, z, X, beta) {
    .Call('_dPLR_PairwiseLikDeriv', PACKAGE = 'dPLR', yvec, z, X, beta)
}

PairwiseLikDeriv1 <- function(yvec, z, X, beta) {
    .Call('_dPLR_PairwiseLikDeriv1', PACKAGE = 'dPLR', yvec, z, X, beta)
}

PairwiseLikDeriv2 <- function(yvec, z, X, beta) {
    .Call('_dPLR_PairwiseLikDeriv2', PACKAGE = 'dPLR', yvec, z, X, beta)
}

PairwiseLikDeriv3 <- function(yvec, z, X, beta) {
    .Call('_dPLR_PairwiseLikDeriv3', PACKAGE = 'dPLR', yvec, z, X, beta)
}

